### PR TITLE
VSCODE-39: replace typescript grammar with mongodb grammar

### PR DESCRIPTION
**Pull request by alenakhineika**
## Description

- Use the MongoDB grammar instead of the TypeScript-MongoDB-injected grammar.
- Download the derived `mongodb.tmLanguage.json` from [vscode-mongodb-language](https://github.com/mongodb-js/vscode-mongodb-language) during `npm run compile`.

### Checklist
- [ ] New tests and/or benchmarks are included
- [x] Documentation is changed or added

## Motivation and Context

- [ ] Bugfix
- [x] New feature
- [ ] Dependency update
- [ ] Misc

## Types of changes

- [ ] *Backport Needed*
- [ ] Patch (non-breaking change which fixes an issue)
- [x] Minor (non-breaking change which adds functionality)
- [ ] Major (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by Anemy** [comment]
Do we want to download this every time we compile or can we just reference it from the package json?

**Comment by alenakhineika** [comment]
@Anemy what do you mean by "reference it from the package json"? like, specify a remote url as the location of the grammar? I think we should keep a downloaded grammar inside the project. but maybe we can remove the script from `npm run compile` and run `npm run update-grammar` manually when needed.

**Comment by Anemy** [comment]
@alenakhineika  Ah yeah good call having it in the project is the move. Do you think moving out of compile might be better? It might make it easier to possibly develop offline. I think the risk is that we forget about running it when changes have happened in the grammer.

**Comment by alenakhineika** [comment]
@Anemy yeah this is why i added it to compile script :) but i thought you have concerns. i personally prefer downloading a new version during compilation. the file is small. The script does not delete the old file before downloading, just pipes new data into the current one. so if something wrong with the network we won't end up without the grammar.

**Comment by Anemy** [comment]
Sounds good - thanks for clarifying

**Pull request merged**
