### PR TITLE
VSCODE-198: Use RFC 3986 encoding

### PR DESCRIPTION
**Pull request by alenakhineika**
## Description

To be more stringent in adhering to RFC 3986, replace !, ', (, ), and * with a corresponding character code.

Related issue: https://github.com/mongodb-js/vscode/issues/169

### Checklist
- [ ] New tests and/or benchmarks are included
- [ ] Documentation is changed or added

## Motivation and Context

- [ ] Bugfix
- [ ] New feature
- [x] Dependency update
- [ ] Misc

## Types of changes

- [ ] *Backport Needed*
- [x] Patch (non-breaking change which fixes an issue)
- [ ] Minor (non-breaking change which adds functionality)
- [ ] Major (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Review by Anemy — APPROVED** [review]
Nice! Tried with a few different configurations, including the one in the issue and they're working well. (can launch MongoDB Shell as well).

Unrelated, but it looks like we're keeping app name in the connection string when it's copied. Created VSCODE-207 for that.

**Review by rose-m — APPROVED** [review]
Nice! Also tested it and worked 👍 

One thing I noticed: connections that already existed were not updated. I had a connection in there with an `!` in the password _before_ I did the update to this PR version. _After_ the update when I copied the connection string it still had the pure `!` in it and it was not encoded. Is that intended? 🤔

**Comment by alenakhineika** [comment]
@rose-m good catch! looks like derived properties stored as well to disk and not being calculated on the fly.

**Comment by alenakhineika** [comment]
@rose-m pushed an update, please test again.

**Comment by rose-m** [comment]
Yes, it works now 🎉

**Pull request merged**
