### PR TITLE
Adjusted linkId for Atlas CTA in Help panel

### PR DESCRIPTION
**Pull request by mmarcon**
## Description

The `linkId` of the Atlas CTA in the help panel to distinguish it from the CTA in the connect screen in Amplitude.

### Checklist
- [ ] New tests and/or benchmarks are included
- [ ] Documentation is changed or added

## Motivation and Context
- [ ] Bugfix
- [ ] New feature
- [ ] Dependency update
- [x] Misc

## Types of changes

- [ ] *Backport Needed*
- [x] Patch (non-breaking change which fixes an issue)
- [ ] Minor (non-breaking change which adds functionality)
- [ ] Major (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by alenakhineika** [comment]
Shouldn't we change this place as well?

https://github.com/mongodb-js/vscode/blob/master/src/views/webview-app/components/help-panel/help-panel.tsx#L160

**Comment by mmarcon** [comment]
@alenakhineika If I understand correctly what that file does, it's the one that shows this:
image

If that's the case then no, we should not change the id in that place too because the reason for this tweak is exactly to distinguish the 2 links.

**Review by Anemy — COMMENTED** [review]
lgtm. the linkIds on the other `HelpTree` events are good right? Do we want to postfix all of the link ids in the help panel with `HelpTree`? 
Ex:
`whatsNew` -> `whatsNewHelpTree`
Might help distinguishing events from the new overview page links.

**Comment by mmarcon** [comment]
Good point. I'll change them all.

**Review by Anemy — APPROVED** [review]

**Comment by mmarcon** [comment]
Never mind, I just realized that we also have a `screen` property set to `helpPanel`. That's all I need. I will close this PR.

**Pull request closed without merging**
