### PR TITLE
VSCODE-101: Update a playground template

### PR DESCRIPTION
**Pull request by alenakhineika**
## Description

- Add the `db.sales.drop()` command to a playground template to allow users to run a template script more than once. Since running a script adds data to a collection and all the next runs documents with the same keys can not be inserted and causes the duplicate key error.
- Add a comment to the beginning of the template that reminds users to be connected before running a playground. Only connected users can run a playground or benefit from the completion feature.
- Add a comment that tells users how to use the completion feature inside snippets and string literals.

### Checklist
- [ ] New tests and/or benchmarks are included
- [x] Documentation is changed or added

## Motivation and Context

- [ ] Bugfix
- [ ] New feature
- [ ] Dependency update
- [x] Misc

## Types of changes

- [ ] *Backport Needed*
- [ ] Patch (non-breaking change which fixes an issue)
- [x] Minor (non-breaking change which adds functionality)
- [ ] Major (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by Anemy** [comment]
Is there a chance someone might have a `sales` db already and we drop unintended data? Maybe we could use a more obscure or namespaced name or  we could delete the documents by ids. Looks good - thanks for bumping the dependencies.

**Comment by alenakhineika** [comment]
@Anemy @mmarcon how about `salesCollectionForPlayground` collection name instead of `sales`.

**Comment by mmarcon** [comment]
I would use a different database.

Essentially, just change the `use()` call.

```javascript
use('mongodbVscodePlaygroundDB');
```

What do you think?

**Comment by alenakhineika** [comment]
LGTM, updated.

**Pull request merged**
